config/routes.rb
Myapp::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

 	resources :faqs
  resources :blogs
  resources :tags
  resources :courses do
        collection do
          get 'course_payment'
          get "confirm_course_payment"
         
        end
         member do
           get "confirm_course_payment"
          end
      end
  resources :topics
  resources :tutorials
  resources :groups
  resources :under_constructions
  resources :o_classes
  resources :comments
	authenticated :user do
		root :to => 'screens#home'
	end
	root :to => 'screens#home'
	match '/about', :to => 'screens#about'
	match '/privacy', :to => 'screens#privacy'
	match '/terms', :to => 'screens#terms'
  #match '/faq', :to => 'screens#faq'
  match '/construction', :to => 'screens#construction'  
  devise_for :users
  resources :users
  match '/auth/:provider/callback' => 'authentication#create'
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  desc       :string(255)
#

class Topic < ActiveRecord::Base
  attr_accessible :name, :desc
  has_many :relationships
  has_many :courses, through: :relationships
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.order(:name)
  end

  def show
    @topic = Topic.find(params[:id])
    @countCoursesPerPage = 5
    #@courses_for_topic = @topic.courses.paginate(page: params[:page], per_page: 5)
    @courses_for_topic = @topic.courses.paginate(page: params[:page], per_page: 5)
    @topics = Topic.order(:name)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
      redirect_to courses_path, notice: "Successfully created topic."
    else
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params[:topic])
      redirect_to @topic, notice: "Successfully updated topic."
    else
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_url, notice: "Successfully destroyed topic."
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="container">
<div class="row">
    <div class="span6 offset3">
<%= form_for @topic, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                topics_path, :class => 'btn' %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/topics/edit.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/topics/index.html.erb
<div class="row">
<div class="span12">
<ul class="nav nav-pills .pull-left">
  <li >
<%= link_to "Users", users_path %>
</li><li >
<%= link_to "Add New Course", new_course_path %>
</li><li class="active">
 <%= link_to "Manage Category", topics_path %>
 </li><li >
 <%= link_to "New Category",new_topic_path %>
 </li>
 </ul>
<%- model_class = Topic -%>
<div class="page-header">
</div>
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.id, topic_path(topic) %></td>
        <td><%= topic.name %></td>
        <td><%=l topic.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_topic_path(topic), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      topic_path(topic),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/topics/new.html.erb
<div class="row">
<div class="span12">
<ul class="nav nav-pills .pull-left">
  <li >
<%= link_to "Users", users_path %>
</li><li >
<%= link_to "Add New Course", new_course_path %>
</li><li >
 <%= link_to "Manage Category", topics_path %>
 </li><li class="active"	>
 <%= link_to "New Category",new_topic_path %>
 </li>
 </ul>
<%- model_class = Topic -%>

<%= render :partial => 'form' %>
</div>
</div>

app/views/topics/show.html.erb
<% provide(:title, 'Courses for ' + @topic.name) %>
<%- model_class = Topic -%>
<div class="container">

  <div class="row">
        <ul class="nav nav-pills .pull-right">
          <li class="active">
            <%= link_to "Courses", courses_path %>
          </li>
          <li><%= link_to "Tutorials", tutorials_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Online Classes", o_classes_path %></li>
          <% end %>
          <li><%= link_to "Blog", blogs_path %></li>
           <li ><%= link_to "Coaches", users_path %></li>
        </ul>
      </div>

  <div class="page-header">
    <% @topicStructure = @topic.name + " ( #{@topic.courses.where(ispublished: 1).size} )" %>
    <h3>Courses related to category: <%= @topicStructure %></h3>
  </div>
  <% if signed_in? && current_user.user_type == 3 #Admin %>
    <div class="form-actions">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  courses_path, :class => 'btn'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_topic_path(@topic), :class => 'btn' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  topic_path(@topic),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
    </div>
  <% end %>
  
  
  <div class="row">
        <div class="span8">
            
            <% if @topic.courses.where(ispublished: 1).size >= 1 %>
                <div class="well">
                    <% if signed_in? && current_user.user_type == 1 #Teacher %>
                      <p><%= link_to "Add New Course", new_course_path , class: "move-to-right-top"%></p>
                    <% end %>
                    
                    <%= render @topic.courses.where(ispublished: 1) %>

                    <% @topic.courses.each do |course| %>
                      <% if ((course.id % @countCoursesPerPage) == 0 ) %>
                        <% if signed_in? && current_user.user_type == 1 #Teacher %>
                          <p><%= link_to "Add New Course", new_course_path , class: "move-to-right-bottom"%></p>
                        <% end %>
                      <% end %>
                    <% end %>
                    
                    <div class="clearfix"></div>
                </div>
            <% else %>
                <div class="alert alert-alert">
                  No Course in this category yet!!!!
                </div>
            <% end %>
        </div><!-- <div class="span8"> -->

        <div class="span3">
            <div class="">

               <!--  <form class="navbar-search pull-left">
                  <input type="text" class="search-query" placeholder="Search">
                </form>
                <div class="clearfix"></div> -->

                <div class="tabbable"> <!-- Only required for left/right tabs -->
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#categories" data-toggle="tab">Categories</a></li>
                    <li><a href="#upcomingcourses" data-toggle="tab">Upcoming Courses</a></li>
                  </ul>
                  <div class="tab-content">

                    <div class="tab-pane active" id="categories">
                      
                      <div class="categories">
                          
                          <ul class="nav nav-list">
                              <li class="nav-header"></li>
                              <li><%= link_to "All" + " ( #{Course.where(ispublished: 1).all.size} )", courses_path %></a></li>
                              <% @topics.each do |topic| %>
                                <% @topicStructure = topic.name + " ( #{topic.courses.where(ispublished: 1).size } )" %>
                                <% if topic.id == @topic.id %>
                                  <li class="active"><a href="#"><%= link_to @topicStructure, topic %></a></li>
                                <% else %>
                                  <li><a href="#"><%= link_to @topicStructure, topic %></a></li>
                                <% end %>
                              <% end %>
                          </ul>
                          <br/>
                          <!-- <button id="createTopicbottom" class="btn btn-info" type="button">Add new Topic
                          </button> -->
                          <% if signed_in? && current_user.user_type == 3 #Admin %>
                            <%= link_to "Manage Category", topics_path, class: "btn btn-info" %>
                          <% end %>
                      </div>

                    </div><!-- <div class="tab-pane active" id="categories"> -->

                    <div class="tab-pane" id="upcomingcourses">
                      
                      <div class="upcoming">
                          <% Course.where(ispublished: 0).all.each do |t| %>
                              <div class="upcoming-widget">
                                <div class="widget-thumbnail">
                                  <!-- <img src="homeOnline.jpg" width="70px" height="100px"> -->
                                  <!--#link_to image_tag("homeOnline.jpg", border 0), {action: '#', controller: '#'},class: '#'-->
                                  <%= link_to image_tag("#{t.image}", border: 0, width: "50", height: "50")%>
                                </div><!-- end .widget-thumbnail -->
                                <div class="widget-body">
                                  <h4><%= t.title %></h4>
                                  <span class="label label-info"><%= t.releasemonth %></span>
                                </div>
                                <div class="clearfix"></div>
                              </div>
                          <% end %>
                      </div>
                    </div><!-- <div class="tab-pane" id="categories"> -->
                  
                  </div><!--<div class="tab-content"> -->
                </div><!-- Only required for left/right tabs -->

                
          </div>
        </div><!-- <div class="span3"> -->
      </div><!-- <div class="row"> -->

</div>