config/routes.rb
Myapp::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

 	resources :faqs
  resources :blogs
  resources :tags
  resources :courses do
        collection do
          get 'course_payment'
          get "confirm_course_payment"
         
        end
         member do
           get "confirm_course_payment"
          end
      end
  resources :topics
  resources :tutorials
  resources :groups
  resources :under_constructions
  resources :o_classes
  resources :comments
	authenticated :user do
		root :to => 'screens#home'
	end
	root :to => 'screens#home'
	match '/about', :to => 'screens#about'
	match '/privacy', :to => 'screens#privacy'
	match '/terms', :to => 'screens#terms'
  #match '/faq', :to => 'screens#faq'
  match '/construction', :to => 'screens#construction'  
  devise_for :users
  resources :users
  match '/auth/:provider/callback' => 'authentication#create'
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
end

app/models/tutorial.rb
# == Schema Information
#
# Table name: tutorials
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  author         :string(255)
#  image          :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  ispublished    :integer          default(0)
#  releasemonth   :string(255)      default("December")
#  desc           :text
#  difficulty     :string(255)
#  estimated_time :integer
#

class Tutorial < ActiveRecord::Base
  attr_accessible :author, :desc, :image, :title, :group_ids, :user_id, :ispublished, :releasemonth, :difficulty, :estimated_time
  has_many :groupings
  has_many :groups, through: :groupings
  belongs_to :user

  #before_save { |course| course.category = category.downcase }

  validates :title, presence: true, length: { maximum: 100 }
  validates :author, presence: true, length: { maximum: 100 }
  validates :desc, presence: true, length: { maximum: 1000 }

  default_scope order: 'tutorials.created_at DESC'
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
	before_filter :signed_in_user, only: [:create, :edit,:update,:delete]

	def index
		@countTutorialsPerPage = 5
    	@tutorials = Tutorial.where(ispublished: 1).paginate(page: params[:page], per_page: 5)
		@groups = Group.order(:name)
  	end


	def new
		@tutorial = Tutorial.new
	end


	def create
		@tutorial = Tutorial.new(params[:tutorial])
		if @tutorial.save
			flash[:success] = "Tutorial added successfully!!!!"
			redirect_to @tutorial
		else
			render 'new'
		end
	end

	def edit
    	@tutorial = Tutorial.find(params[:id])
  	end

  	def update
	    @tutorial = Tutorial.find(params[:id])
	    if @tutorial.update_attributes(params[:tutorial])
	      redirect_to @tutorial, notice: "Successfully updated Tutorial."
	    else
	      render :edit
	    end
  	end


	def show
		@tutorial = Tutorial.find(params[:id])
		# Just to redirect, needed due to button click event
		# @courses = Course.paginate(page: params[:page], per_page: 3)
		# @topics = Topic.all
		#@courses = Course.all
	end

	def destroy
	    @tutorial = Tutorial.find(params[:id])
	    @tutorial.destroy
	    flash[:success] = "Successfully destroyed tutorial."
	    redirect_to tutorials_url
  	end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_tutorial.html.erb
<%- model_class = Tag -%>
<div class="well-course">  
  <h4><%= link_to tutorial.title, tutorial %>
        <!-- <img src="images/dmbtest.gif" width="45px" height="45px" /> -->
        <%= link_to image_tag("#{tutorial.image}", width: "30", height: "30")%>
    </h4>
  <div class="clearfix">
  </div>
    <div class="entry-meta">
        <span class="meta-author">
          <a href="#" title="#" rel="author"><%= link_to User.find_by_id(tutorial.user_id).name,  User.find_by_id(tutorial.user_id) %></a>
        </span>
        
        <span class="meta-categories">
        <% tutorial.groups.each do |group| %>
          <a href="#" title="#"><%= link_to group.name , group %></a>
            <% if tutorial.groups.last.name == group.name %>
            <% else %>
              <span class="cat-sep">\</span>
            <% end %>
        <% end %>
      </span>              
    </div>
    
    <div class="clearfix"></div>
    <div class="entry-wrap">
      <div class="entry-thumbnail">
          <a title="#" href="#">
            <!-- <img src="math.jpg" width="100" height="100"> -->
            <%= link_to image_tag("#{tutorial.image}", border: 0, width: "100", height: "100")%>
          </a>
      </div><!-- end .entry-thumbnail -->
        <div class="entry-content has-post-image">
          <p>Difficulty: <%= tutorial.difficulty %>
            <br/>Estimated Time to complete: <%= "#{tutorial.estimated_time}" + " minutes" %></p>
          <p class="muted" style="text-align: justify;"><%= tutorial.desc %></p>
          <% if signed_in? %>
            <%= link_to "Start Tutorial", '#', class: "btn btn-primary btn-success" %>
          <% else %>
            <%= link_to "Join to Access", new_user_registration_path , class: "btn btn-primary btn-info" %>
            <%= link_to "SignIn to start", new_user_session_path, class: "btn btn-primary btn-success" %>
          <% end %>
          <% if signed_in? && current_user.id == User.find_by_id(tutorial.user_id).id %>
              <p style="float:right;margin:0px;">
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_tutorial_path(tutorial), :class => 'btn btn-mini' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    tutorial_path(tutorial),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-mini' %>
              </p>
          <% end %>
          
        </div><!-- end .entry-content -->         
    </div>
    <div class="clearfix"></div>
</div>

app/views/tutorials/edit.html.erb
<% provide(:title, 'Edit Tutorial') %>

<div class="row">
<div class="span4 offset3">
<%= form_for(@tutorial) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title, "Tutorial Title" %>
<%= f.text_field :title %>

<%= f.label :author, "Author Name" %>
<%= f.text_field :author %>

<%= f.label :desc, "Tutorial Description" %>
<%= f.text_area :desc %>

<%= f.label :image, "Tutorial Image" %>
<%= f.text_field :image %>

<%= f.label :group_ids, "Topics" %>
<%= f.collection_select :group_ids, Group.order(:name), :id, :name, {}, {multiple: true} %>

<br/><br/>
<%= f.submit "Edit Tutorial", class: "btn btn-large btn-info" %>
<% end %>
</div>
</div>

app/views/tutorials/index.html.erb
<% provide(:title, 'Tutorials') %>
<div class="container">
      <div class="row">
        <ul class="nav nav-pills .pull-right">
          <li>
            <%= link_to "Courses", courses_path %>
          </li>
          <li class="active"><%= link_to "Tutorials", tutorials_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Online Classes", o_classes_path %></li>
          <% end %>
          <li><%= link_to "Blog", blogs_path %></li>
        </ul>
      </div>

      <div class="row">
        <div class="span8">
            <% if @tutorials.size >= 1 %>
                  
                  <div class="well">
                      <% if signed_in? && current_user.user_type == 1 #Teacher %>
                        <p><%= link_to "Add New Course", new_tutorial_path , class: "move-to-right-top"%></p>
                      <% end %>

                      <%= will_paginate %>
                            <%= render @tutorials %>
                      <%= will_paginate %>
                      
                      <% @tutorials.each do |tutorial| %>
                        <% if ((tutorial.id % @countTutorialsPerPage) == 0 ) %>
                          <% if signed_in? && current_user.user_type == 1 #Teacher %>
                            <p><%= link_to "Add New Course", new_tutorial_path , class: "move-to-right-bottom"%></p>
                          <% end %>
                        <% end %>
                      <% end %>
                      
                      <div class="clearfix"></div>
                  </div>
            <% else %>
              <div class="alert alert-error">
                    No tutorials published yet. Check upcoming tutorials!!!!
              </div>
            <% end %>
        </div><!-- <div class="span8"> -->

        <div class="span3">
            <div class="">

               <!--  <form class="navbar-search pull-left">
                  <input type="text" class="search-query" placeholder="Search">
                </form>
                <div class="clearfix"></div> -->

                <div class="tabbable"> <!-- Only required for left/right tabs -->
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#categories" data-toggle="tab">Categories</a></li>
                    <li><a href="#upcomingcourses" data-toggle="tab">Upcoming Tutorials</a></li>
                  </ul>
                  <div class="tab-content">

                    <div class="tab-pane active" id="categories">
                      

                      <div class="categories">
                          <% if @groups.size > 1 %>
                            <ul class="nav nav-list">
                              <li class="nav-header"></li>
                              <li class="active"><%= link_to "All" + " ( #{Tutorial.where(ispublished: 1).all.size} )", tutorials_path %></a></li>
                              <% @groups.each do |group| %>    
                                  <% @groupStructure = group.name + " ( #{ group.tutorials.where(ispublished: 1).size} )" %>
                                  <li><a href="#"><%= link_to @groupStructure, group %></a></li>
                              <% end %>
                            </ul>
                          <% else %>
                            <div class="alert alert-error">
                                  No Categoried defined!!
                            </div>
                          <% end %>
                          <br/>
                          
                          <% if signed_in? && current_user.user_type == 3 #Admin %>
                            <%= link_to "Manage Category", groups_path, class: "btn btn-info" %>
                          <% end %>
                      </div>

                    </div><!-- <div class="tab-pane active" id="categories"> -->

                    <div class="tab-pane" id="upcomingcourses">
                      
                      <div class="upcoming">
                          <% Tutorial.where(ispublished: 0).all.each do |t| %>
                              <div class="upcoming-widget">
                                <div class="widget-thumbnail">
                                  <!-- <img src="homeOnline.jpg" width="70px" height="100px"> -->
                                  <!--#link_to image_tag("homeOnline.jpg", border 0), {action: '#', controller: '#'},class: '#'-->
                                  <%= link_to image_tag("#{t.image}", border: 0, width: "50", height: "50")%>
                                </div><!-- end .widget-thumbnail -->
                                <div class="widget-body">
                                  <h4><%= t.title %></h4>
                                  <span class="label label-info"><%= t.releasemonth %></span>
                                </div>
                                <div class="clearfix"></div>
                              </div>
                          <% end %>
                      </div>
                    </div><!-- <div class="tab-pane" id="categories"> -->
                  
                  </div><!--<div class="tab-content"> -->
                </div><!-- Only required for left/right tabs -->

                
          </div>
        </div><!-- <div class="span3"> -->
      </div><!-- <div class="row"> -->
</div><!-- <div class="container"> -->

app/views/tutorials/new.html.erb
<% provide(:title, 'Create Tutorial') %>
<div class="row">
<div class="span4 offset3">
<%= form_for(@tutorial) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title, "Tutorial Title" %>
<%= f.text_field :title %>

<%= f.label :author, "Author Name" %>
<%= f.text_field :author %>

<%= f.label :desc, "Tutorial Description" %>
<%= f.text_area :desc %>

<%= f.label :image, "Tutorial Image" %>
<%= f.text_field :image %>

<%= f.label :group_ids, "Topics" %>
<%= f.collection_select :group_ids, Group.order(:name), :id, :name, {}, {multiple: true} %>

<br/><br/>
<p><%= f.submit %></p>
<% end %>
</div>
</div>
<center>
<p><%= link_to "Back to Tutorials", tutorials_path %></p>
</center>

app/views/tutorials/show.html.erb
<% provide(:title, 'Show Tutorial') %>
<div class="row">
        <ul class="nav nav-pills .pull-right">
          <li>
            <%= link_to "Courses", courses_path %>
          </li>
          <li class="active"><%= link_to "Tutorials", tutorials_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Online Classes", o_classes_path %></li>
          <% end %>
          <li><%= link_to "Blog", blogs_path %></li>
           <li ><%= link_to "Coaches", users_path %></li>
        </ul>
</div>
<div class="container">
	<div class="row">
		<div class="span12">
			<div class="hero-unit" align="center">
				<h1>Canvas Page will appear here!!!!</h1>
				<h2><%= link_to "Back to Tutorials", tutorials_path %></h2>
			</div>
		</div>
	</div>
</div>