config/routes.rb
Myapp::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

 	resources :faqs
  resources :blogs
  resources :tags
  resources :courses do
        collection do
          get 'course_payment'
          get "confirm_course_payment"
         
        end
         member do
           get "confirm_course_payment"
          end
      end
  resources :topics
  resources :tutorials
  resources :groups
  resources :under_constructions
  resources :o_classes
  resources :comments
	authenticated :user do
		root :to => 'screens#home'
	end
	root :to => 'screens#home'
	match '/about', :to => 'screens#about'
	match '/privacy', :to => 'screens#privacy'
	match '/terms', :to => 'screens#terms'
  #match '/faq', :to => 'screens#faq'
  match '/construction', :to => 'screens#construction'  
  devise_for :users
  resources :users
  match '/auth/:provider/callback' => 'authentication#create'
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	before_filter :current_user, only: [:create, :edit,:update,:delete]
   ActiveMerchant::Billing::Integrations


	def index
		@countCoursesPerPage = 5
       @courses = Course.where(ispublished: 1).paginate(page: params[:page], per_page: 5)
		@topics = Topic.order(:name)
  	end
	def new
		@course = Course.new
	end


	def create
		@course = current_user.courses.build(params[:course])
		@course.user_id = current_user.id
		if @course.save
			flash[:success] = "Course added successfully!!!!"
			redirect_to @course
		else
			render 'new'
		end
	end
	

	def edit
    	@course = Course.find(params[:id])
  	end

  	def update
	    @course = Course.find(params[:id])
	    if @course.update_attributes(params[:course])
	      redirect_to @course, notice: "Successfully updated topic."
	    else
	      render :edit
	    end
  	end


	def show
		@course = Course.find(params[:id])
		@countCommentsPerPage = 5
		@comments = @course.comments.paginate(page: params[:page], per_page: 5)
		@count = @course.comments.count
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])
		if @course.update_attributes(params[:course])
			redirect_to @course, notice: "Successfully updated topic."
		else
			render :edit
		end
	end

	def show
		@course = Course.find(params[:id])

		@countCommentsPerPage = 5
		@comments = @course.comments.paginate(page: params[:page], per_page: 5)
		@count = @course.comments.count
		if signed_in? 
			unless RatingCache.find_by_cacheable_id(@course.id) == nil
				@qty = RatingCache.find_by_cacheable_id(@course.id).qty
			end
			
			@rated = Rate.find_by_rater_id(current_user.id)
		end
		# Just to redirect, needed due to button click event
		# @courses = Course.paginate(page: params[:page], per_page: 3)
		# @topics = Topic.all
		#@courses = Course.all
	end

	def destroy
	    @course = Course.find(params[:id])
	    @course.destroy
	    flash[:success] = "Successfully destroyed course."
	    redirect_to courses_url
  	end
  	def course_payment
	  
  	end
  	def confirm_course_payment
  		@notification = ActiveMerchant::Billing::Integrations::Ccavenue::Notification.new(request.raw_post)
     if @notification.payment_id.present?
      @order = Course.find_by_order_id(@notification.payment_id)
      if @notification.complete? and @notification.valid?
        @order.confirm!
      else
       @order.reject!
      end
    end
	  
  	end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div class="thumbnail"> 
  <%- model_class = Tag -%>
  <div class="well-course">  
   <h4><%= link_to course.title, course %>
     <!-- <img src="images/dmbtest.gif" width="45px" height="45px" /> -->
     <%= link_to image_tag("#{course.image}", width: "30", height: "30")%>
   </h4>
   <div class="clearfix">
   </div>
   <div class="entry-meta">
    <span class="meta-author">
     <a href="#" title="#" rel="author"><%= link_to User.find_by_id(course.user_id).name,  User.find_by_id(course.user_id) %></a>
   </span>
   <span class="meta-categories">
    <% course.topics.each do |topic| %>
    <a href="#" title="#"><%= link_to topic.name , topic %></a>
    <% if course.topics.last.name == topic.name %>
    <% else %>
    <span class="cat-sep">\</span>
    <% end %>
    <% end %>
  </span>              
</div>
<div class="clearfix"></div>
<table class="table table-hover"> 
  <tr>
    <td>  
     <div class="entry-thumbnail">
      <div align="center">
       <a>
        <%= link_to image_tag("#{course.image}", border: 0, width: "100", height: "100")%> 
        <% unless url_for(:only_path => true, :overwrite_params=> { }) == '/courses?'  %>
        <br align = "center">Has <%= pluralize(@qty, "Ratings") %>
        <% end %>
        <%= rating_for course, "rate" %> 
        <% unless url_for(:only_path => true, :overwrite_params=> { }) == '/courses?'  %>
        <% if @rated == nil  %>
        Rate This Course
        <% else  %>
        Course Rated
        <% end %>
        <% end %>
      </a>
    </div>

  </div>
  
</td>
<td>
  <!-- end .entry-thumbnail -->

  <div class="entry-content has-post-image">
    <p class="muted" style="text-align: justify;"><%= course.desc %></p>
    <% if signed_in? %>
    <%= link_to "Start Course", '#', class: "btn btn-primary btn-success" %>
    <% else %>
    <%= link_to "Join to Access", new_user_registration_path , class: "btn btn-primary btn-info" %>
    <%= link_to "SignIn to start", new_user_session_path, class: "btn btn-primary btn-success" %>
    <% end %>
    <% if signed_in? && current_user.id == User.find_by_id(course.user_id).id %>
    <p style="float:right;margin:0px;">
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
      edit_course_path(course), :class => 'btn btn-mini' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
      course_path(course),
      :method => 'delete',
      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
      :class => 'btn btn-mini' %>
    </p>
    <% end %>

  </div><!-- end .entry-content -->         
</div>
</td>
</tr>
</table>
</div>
</div>
<br>

app/views/courses/comment.html.erb
<h1>Review</h1>
<div class="row">
<div class="span6 offset3">
<%= form_for (:comment, url: comment_path) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :review %>
<%= f.text_area :review %>
<%= f.submit "Add", class: "btn btn-large btn-primary" %>
<% end %>
</div>
</div>

app/views/courses/course_payment.html.erb
<% payment_service_for 1, "dddd",
    :amount => "300",
    :currency => 'INR',
    :service => :ccavenue do |service| %>    
  <%  service.customer :name => "hitesh",
             :email => "test@test.com",
             :phone =>  "9893171496" %>    
  <%  service.redirect :return_url => confirm_course_payment_course_url(Course.first) %>
  <%= submit_tag 'Proceed to payment' %>
<% end %>

app/views/courses/edit.html.erb
<% provide(:title, 'Create Course') %>
<div class="row">
<div class="span4 offset3">
<%= form_for(@course) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title, "Course Title" %>
<%= f.text_field :title %>

<%= f.label :author, "Author Name" %>
<%= f.text_field :author %>

<%= f.label :desc, "Course Description" %>
<%= f.text_area :desc %>

<%= f.label :image, "Course Image" %>
<%= f.text_field :image %>

<%= f.label :topic_ids, "Topics" %>
<%= f.collection_select :topic_ids, Topic.order(:name), :id, :name, {}, {multiple: true} %>

<br/><br/>
<%= f.submit "Edit Course", class: "btn btn-large btn-info" %>
<% end %>
</div>
</div>

app/views/courses/index.html.erb
<div class="container">
  <div class="row">
    <div class="span8">
      <% if @courses.size >= 1 %>

      <div class="well">
        
        <%= will_paginate %>
       
          <%= render @courses %>
      
        <%= will_paginate %>
        <% @courses.each do |course| %>
        <% if ((course.id % @countCoursesPerPage) == 0 ) %>
        
        <% end %>
        <% end %>
        <div class="clearfix"></div>
      </div>
      <% else %>
      <div class="alert alert-error">
        No courses published yet. Check upcoming courses!!!!
      </div>
      <% end %>
    </div><!-- <div class="span8"> -->

    <div class="span4">
      <div class="well">

               <!--  <form class="navbar-search pull-left">
                  <input type="text" class="search-query" placeholder="Search">
                </form>
                <div class="clearfix"></div> -->

                <div class="tabbable"> <!-- Only required for left/right tabs -->
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#categories" data-toggle="tab">Categories</a></li>
                    <li><a href="#upcomingcourses" data-toggle="tab">Upcoming Courses</a></li>
                  </ul>
                  <div class="tab-content">

                    <div class="tab-pane active" id="categories">


                      <div class="categories">
                        <% if @topics.size > 1 %>
                        <ul class="nav nav-list">
                          <li class="nav-header"></li>
                          <li class="active"><%= link_to "All" + " ( #{Course.where(ispublished: 1).all.size} )", courses_path %></a></li>
                          <% @topics.each do |topic| %>    
                          <% @topicStructure = topic.name + " ( #{ topic.courses.where(ispublished: 1).size} )" %>
                          <li><a href="#"><%= link_to @topicStructure, topic %></a></li>
                          <% end %>
                        </ul>
                        <% else %>
                        <div class="alert alert-error">
                          No Categoried defined!!
                        </div>
                        <% end %>
                        <br/>
                          <!-- <button id="createTopicbottom" class="btn btn-info" type="button">Add new Topic
                        </button> -->
                       
                      </div>

                    </div><!-- <div class="tab-pane active" id="categories"> -->

                    <div class="tab-pane" id="upcomingcourses">

                      <div class="upcoming">
                        <% Course.where(ispublished: 0).all.each do |t| %>
                        <div class="upcoming-widget">
                          <div class="widget-thumbnail">
                            <!-- <img src="homeOnline.jpg" width="70px" height="100px"> -->
                            <!--#link_to image_tag("homeOnline.jpg", border 0), {action: '#', controller: '#'},class: '#'-->
                            <%= link_to image_tag("#{t.image}", border: 0, width: "50", height: "50")%>
                          </div><!-- end .widget-thumbnail -->
                          <div class="widget-body">
                            <h4><%= t.title %></h4>
                            <span class="label label-info"><%= t.releasemonth %></span>
                          </div>
                          <div class="clearfix"></div>
                        </div>
                        <% end %>
                      </div>
                    </div><!-- <div class="tab-pane" id="categories"> -->

                  </div><!--<div class="tab-content"> -->
                </div><!-- Only required for left/right tabs -->

                
              </div>
            </div><!-- <div class="span3"> -->
          </div><!-- <div class="row"> -->
        </div><!-- <div class="container"> -->

app/views/courses/new.html.erb
<div class="row">
<div class="span12">
<ul class="nav nav-pills .pull-left">
  <li >
<%= link_to "Users", users_path %>
</li><li class="active">
<%= link_to "Add New Course", new_course_path %>
</li><li>
 <%= link_to "Manage Category", topics_path %>
  </li><li >
 <%= link_to "New Category",new_topic_path %>
 </ul>
<% provide(:title, 'Create Course') %>
<div class="row">
<div class="span4 offset3">
<%= form_for(@course) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title, "Course Title" %>
<%= f.text_field :title %>

<%= f.label :author, "Author Name" %>
<%= f.text_field :author %>

<%= f.label :desc, "Course Description" %>
<%= f.text_area :desc %>

<%= f.label :image, "Course Image" %>
<%= f.text_field :image %>

<%= f.label :topic_ids, "Topics" %>
<%= f.collection_select :topic_ids, Topic.order(:name), :id, :name, {}, {multiple: true} %>

<br/><br/>
<p><%= f.submit %></p>
<% end %>
</div>
</div>
<center>
<p><%= link_to "Back to Courses", courses_path %></p>
</center>
</div>
</div>

app/views/courses/show.html.erb
<% provide(:title, 'Show Course') %>
<div class="container">
	<div class="row">
		<div class="span12">
			<div>
				<%= render @course %>
				<div>
					<div class="row">
						<div class="span5 offset3">

							<%= link_to "Add reveiw",new_comment_path(:commentable=>@course,:commentable_type=>"course"), :locals => {:commentable => @course} %>
							
						</div>
						
					</div>
					<%= render :partial => 'comments/review', :locals => {:commentable => @course} %>
				</div>
				<%= link_to "Back to Courses", courses_path %>
			</div>
		</div>
	</div>
</div>